### ISSUE TITLE
table-layout v3 depends on command-line-usage v6

### ISSUE THREAD

**Issue by jakebailey** [75lb/table-layout#17]
command-line-usage v7 was just released, which depends on v3 of this library, but this library appears to depend on v6 of command-line-usage, which creates a lot of duplication. See: https://npmgraph.js.org/?q=command-line-usage

Any chance this library could also bump its dependency? (Or, not cycle?)

**Comment by 75lb** [comment]
> Any chance this library could also bump its dependency?

Done, thanks for letting me know!
