### ISSUE TITLE
Remove core-js?

### ISSUE THREAD

**Issue by justinfagnani** [75lb/table-layout#5]
Don't want to be a nag about this :P but since 0.12 is now out of maintenance, can it be dropped from support? It'd be great to excise core-js from our dependencies.

**Comment by 75lb** [comment]
yes, leave it with me - will make a start tomorrow (it's 00:49 here atm) releasing new major versions which drop the core-js dep.. v0.12 users will still be able to use the old module versions (but have no upgrade path).

**Comment by 75lb** [comment]
released new versions of table-layout, command-line-usage and command-line-commands - all of which now require node v4.0.0.. bye bye core-js, babel, feature-detection etc. 👋
