### ISSUE TITLE
Upgrade deep-extend

### ISSUE THREAD

**Issue by Tanos42** [75lb/table-layout#6]
It would be great to use deep-extend 0.5.1 due to [https://hackerone.com/reports/311333](https://hackerone.com/reports/311333)

**Comment by 75lb** [comment]
ok, i'll take a look at that.. are you using table-layout in an online, public-facing server application?

**Comment by 75lb** [comment]
[project already installs 0.5.1](https://github.com/75lb/table-layout/blob/master/package.json#L27)
