### ISSUE TITLE
process.stdout.columns and process.stderr.columns are not always available

### ISSUE THREAD

**Issue by kwaping** [75lb/table-layout#9]
I was having some trouble with inconsistent tests using Jest snapshots and I eventually discovered that `process.stdout.columns` and `process.stderr.columns` are not always available.

https://github.com/nodejs/node/issues/2333 is an example of this.

You might want to update your width calculations to handle this situation. I'm trying to do some workarounds but so far haven't had any luck.

Thanks!

**Comment by 75lb** [comment]
Sorry, but I'm not clear how to resolve this. What is your specific issue, and what is the specific fix you require?

In the case `process.stdout.columns` is not available, what terminal width should we default to? Currently, [the library defaults to 80](https://github.com/75lb/table-layout/blob/master/test/bad-input.js#L15). [Code](https://github.com/75lb/table-layout/blob/master/index.js#L49).

**Comment by kwaping** [comment]
Sorry for the lack of details. I have some unit tests which use Jest to compare snapshots of the help text against the actual output. When running this on my laptop in a terminal, everything is fine because `process.stdout.columns` is set to my TTY width. Some of the help text is long, so word-wrapping can get involved with narrower terminals. My terminal width happens to be 183 characters, so there is no wrapping involved.

The issue happens when running these same snapshot tests in Jenkins. Apparently there is no TTY, so `process.stdout.columns` and `process.stderr.columns` is `undefined`. This then reverts to the 80-char default, which causes wrapping and breaks the snapshot comparison.

While writing that, I realized that I can set my terminal to 80 characters and take new snapshots. However, that assumes knowledge of the default width.

I guess the solution might not be for this library, but maybe better implemented in the `command-line-usage` code. A couple of ideas could be:
* Allowing all column widths to be specified min/max/exact
* A default value which could be set by the user, and is clearly explained in the documentation

**Comment by 75lb** [comment]
Fixed and released in table-layout v2.0.1.
